# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\"\xbf\x01\n\x17\x45quipmentIdentification\x12\x14\n\x0c\x65quipment_id\x18\x01 \x01(\t\x12\x34\n\x04type\x18\x02 \x01(\x0e\x32&.EquipmentIdentification.EquipmentType\x12\x12\n\nip_address\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\x05\"6\n\rEquipmentType\x12\x08\n\x04LAMP\x10\x00\x12\x06\n\x02TV\x10\x01\x12\x13\n\x0f\x41IR_CONDITIONER\x10\x02\"5\n\x0e\x45quipmentState\x12\x14\n\x0c\x65quipment_id\x18\x01 \x01(\t\x12\r\n\x05is_on\x18\x02 \x01(\x08\"7\n\x0e\x43ontrolCommand\x12\x14\n\x0c\x65quipment_id\x18\x01 \x01(\t\x12\x0f\n\x07turn_on\x18\x02 \x01(\x08\"<\n\x0fTemperatureData\x12\x14\n\x0c\x65quipment_id\x18\x01 \x01(\t\x12\x13\n\x0btemperature\x18\x02 \x01(\x02\"%\n\x12\x45quipmentDiscovery\x12\x0f\n\x07message\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EQUIPMENTIDENTIFICATION']._serialized_start=19
  _globals['_EQUIPMENTIDENTIFICATION']._serialized_end=210
  _globals['_EQUIPMENTIDENTIFICATION_EQUIPMENTTYPE']._serialized_start=156
  _globals['_EQUIPMENTIDENTIFICATION_EQUIPMENTTYPE']._serialized_end=210
  _globals['_EQUIPMENTSTATE']._serialized_start=212
  _globals['_EQUIPMENTSTATE']._serialized_end=265
  _globals['_CONTROLCOMMAND']._serialized_start=267
  _globals['_CONTROLCOMMAND']._serialized_end=322
  _globals['_TEMPERATUREDATA']._serialized_start=324
  _globals['_TEMPERATUREDATA']._serialized_end=384
  _globals['_EQUIPMENTDISCOVERY']._serialized_start=386
  _globals['_EQUIPMENTDISCOVERY']._serialized_end=423
# @@protoc_insertion_point(module_scope)
